name: habit_tracking
description: A habit tracking application built with Flutter and GetX.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Version information
version: 1.0.0+1

# Environment configuration
environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Core
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  # State Management & Data
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  logger: ^2.0.2
  
  # UI Components
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  pull_to_refresh: ^2.0.0
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  
  # Utils
  uuid: ^4.2.2
  url_launcher: ^6.1.14
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  intl_utils: ^2.8.4
  timeago: ^3.6.0
  
  # Notifications & Permissions
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  
# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  build_runner: ^2.4.6
  
# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/
  
  # Fonts
  # You can add custom fonts later by uncommenting and configuring this section
  # and placing the font files in the assets/fonts/ directory
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700

# Flutter launcher icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon_web.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_windows.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon_macos.png"
  linux:
    generate: true
    image_path: "assets/icons/app_icon_linux.png"

# Flutter native splash configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo_android12.png"
    icon_background_color: "#FFFFFF"
  web:
    image: "assets/images/splash_logo_web.png"
    background_color: "#FFFFFF"
  windows:
    image: "assets/images/splash_logo_windows.png"
    background_color: "#FFFFFF"
  macos:
    image: "assets/images/splash_logo_macos.png"
    background_color: "#FFFFFF"
  linux:
    image: "assets/images/splash_logo_linux.png"
    background_color: "#FFFFFF"
